name: weekend_countdown
description: "IT'S THE FINAL COUNTDOWN"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/digital-7/

  fonts:
    - family: Digital7Mono
      fonts:
        - asset: assets/fonts/digital-7/digital-7 (mono).ttf
